# Site settings
title: From Fitness to Technology
header-img: img/home-bg.png
email: jschles1@ramapo.edu
copyright_name: Jschles1
description: > # this means to ignore newlines until "baseurl:"
  Follow me on my journey as I embark on a new career path to become a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: John_Schles
github_username:  Jschles1
learn_profile: Jschles1
email_username: jschles1@ramapo.edu

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
